In [ ]:
#data frame is just a combination of multiple series

In [1]:
import numpy as np
import pandas as pd

In [3]:
#first we will give a dictionary of input data
data = {"Name" : ['Spidey','Batey', 'Thorey', 'Captain'],
        "Age" : [22,35,100,70],
        "Salary" : [12000,23000,45000,1000000],
        "City" : ["New York","Paris", "Tokyo", "Montreal"]}
#creating a dataframe
df = pd.DataFrame(data)
print(df)

      Name  Age   Salary      City
0   Spidey   22    12000  New York
1    Batey   35    23000     Paris
2   Thorey  100    45000     Tokyo
3  Captain   70  1000000  Montreal

In [13]:
#or we can also use lists for making a dataframe like this

data_list = [['Spidey',22, 45000, "New York"],['Batey',35,23000,'Paris'],['Captain',70,100000, 'Montreal'],["THorey",100, 45000, "Tokyo"]]
df = pd.DataFrame(data_list)
print(df)
print("\n")
#till here we havent given the column names yet
columns = ['Name', "Age", 'Salary', 'City']
df1 = pd.DataFrame(data_list, columns = columns )
print(df1)

         0    1       2         3
0   Spidey   22   45000  New York
1    Batey   35   23000     Paris
2  Captain   70  100000  Montreal
3   THorey  100   45000     Tokyo


      Name  Age  Salary      City
0   Spidey   22   45000  New York
1    Batey   35   23000     Paris
2  Captain   70  100000  Montreal
3   THorey  100   45000     Tokyo

In [17]:
#selecting and indexing of columns
#df1[0] # only this will throw an error because no column is named as 0

df1['Name']

df1[['Name','Age']]

      Name  Age
0   Spidey   22
1    Batey   35
2  Captain   70
3   THorey  100

In [31]:
#creating a new column
df1['Designation'] = ['engnr','doctor','mineworker', 'artist']
print(df1)

      Name  Age  Salary      City Designation
0   Spidey   22   45000  New York       engnr
1    Batey   35   23000     Paris      doctor
2  Captain   70  100000  Montreal  mineworker
3   THorey  100   45000     Tokyo      artist

In [32]:
#remove column
df1.drop('Designation', axis = 1)
#this will only remove and give a snapsot, but will not actually delete that column

# print(df1)

      Name  Age  Salary      City
0   Spidey   22   45000  New York
1    Batey   35   23000     Paris
2  Captain   70  100000  Montreal
3   THorey  100   45000     Tokyo

In [33]:
#to delete a column permanently from the data frame
df1.drop('Designation', axis = 1, inplace = True)
df1

# now it is permanently deleted from the dataframe
#similary a row too can be deleted,  choosing axis = 0

df1.drop(0, axis = 0)

      Name  Age  Salary      City
1    Batey   35   23000     Paris
2  Captain   70  100000  Montreal
3   THorey  100   45000     Tokyo

In [37]:
#row indexing, to locate a row

print(df1.loc[0])

print(df1.loc[[0,1]])

Name        Spidey
Age             22
Salary       45000
City      New York
Name: 0, dtype: object
     Name  Age  Salary      City
0  Spidey   22   45000  New York
1   Batey   35   23000     Paris

In [39]:
#selecting subsets of row and columns

df1.loc[[0,1,2]][['City', 'Salary']]

       City  Salary
0  New York   45000
1     Paris   23000
2  Montreal  100000

In [ ]:
#conditional selection
#if i want all members whose age is greater than 50

print(df1[df1['Age']>50])

print("\n")

#age less than 50 and city paris
print(df1[(df1['Age'] < 50) & (df1['City'] == "Paris")])

      Name  Age  Salary      City
2  Captain   70  100000  Montreal
3   THorey  100   45000     Tokyo


    Name  Age  Salary   City
1  Batey   35   23000  Paris