In [1]:
import numpy as np
import pandas as pd

In [2]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

print(df1)
print("\n")
print(df2)

      name
1    Alice
2      Bob
3  Charlie


   score
2     85
3     90
4     75

In [3]:
#merging and joining are almost the same thing, but merge is based on
#columns while join is based on index only
df1.join(df2, how = 'outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [4]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN